# ==============================================================================
# IMPORTS
# ==============================================================================
import yt_dlp
import sys
import os
import subprocess
import traceback # Used for detailed error reporting

# ==============================================================================
# CONFIGURATION & PATHS
# ==============================================================================
# This section intelligently sets up paths so the script/exe is fully portable.

# --- Global Constants ---
# These values can be easily changed to alter the application's behavior.
HANDBRAKE_PRESET_NAME = "Resolve Ready"
HANDBRAKE_OUTPUT_FOLDER = "Handbraked"

# --- Dynamic Path Resolution ---
# Determines if the script is running as a standalone .exe or a normal .py file.
# This is crucial for finding bundled data files like HandBrakeCLI.exe.
IS_RUNNING_AS_EXE = getattr(sys, 'frozen', False)

if IS_RUNNING_AS_EXE:
    # If running as a bundled .exe created by PyInstaller:
    # APP_DIR is the directory where the user ran the .exe file from.
    # This is where we will look for videos and save the output.
    APP_DIR = os.path.dirname(sys.executable)
    # BUNDLE_DIR is the path to the temporary folder where PyInstaller
    # has extracted the bundled files (like HandBrakeCLI).
    BUNDLE_DIR = sys._MEIPASS
else:
    # If running as a standard .py script:
    # The application and bundle directories are the same.
    APP_DIR = os.path.dirname(os.path.abspath(__file__))
    BUNDLE_DIR = APP_DIR

# --- Asset Paths ---
# Build the full paths to the required executable and preset file.
# These assets are expected to be bundled with the application.
HANDBRAKE_CLI_PATH = os.path.join(BUNDLE_DIR, "HandBrakeCLI.exe")
HANDBRAKE_PRESET_FILE = os.path.join(BUNDLE_DIR, "resolve_preset.json")


# ==============================================================================
# CORE FUNCTIONS
# ==============================================================================

def run_handbrake_conversion(source_filepath):
    """
    Converts a single video file using HandBrake CLI.

    This function builds the command, runs the HandBrake process, filters its
    output to show only a clean progress bar, and handles success or failure.

    Args:
        source_filepath (str): The full path to the video file to be converted.
    """
    # 1. --- Validation ---
    # Ensure that the required HandBrake files exist before attempting to run.
    if not os.path.exists(HANDBRAKE_CLI_PATH) or not os.path.exists(HANDBRAKE_PRESET_FILE):
        print("\nERROR: HandBrakeCLI.exe or resolve_preset.json could not be found in the application bundle.")
        return

    print(f"\n--- Starting HandBrake conversion... ---")

    # 2. --- Path Construction ---
    # Define where the final, converted file will be saved.
    output_dir = os.path.join(APP_DIR, HANDBRAKE_OUTPUT_FOLDER)
    os.makedirs(output_dir, exist_ok=True) # Create the output folder if it doesn't exist.

    # Create a new filename for the converted video.
    base_filename = os.path.splitext(os.path.basename(source_filepath))[0]
    output_filepath = os.path.join(output_dir, f"{base_filename}_Handbraked.mp4")

    # 3. --- Command Assembly ---
    # Create the list of arguments to pass to the HandBrake command-line interface.
    command = [
        HANDBRAKE_CLI_PATH,
        "-i", source_filepath,
        "-o", output_filepath,
        "--preset-import-file", HANDBRAKE_PRESET_FILE,
        "-Z", HANDBRAKE_PRESET_NAME
    ]

    # 4. --- Process Execution and Output Filtering ---
    # Use subprocess.Popen to run HandBrake and capture its output in real-time.
    # This gives us fine-grained control over what is displayed to the user.
    process = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,        # Capture standard output.
        stderr=subprocess.STDOUT,       # Redirect errors to the same stream as standard output.
        universal_newlines=True,      # Decode output as text.
        encoding='utf-8',             # Specify the text encoding.
        # This flag prevents a new console window from flashing on Windows.
        creationflags=subprocess.CREATE_NO_WINDOW if sys.platform == 'win32' else 0
    )

    # Read the output line-by-line as it's generated by HandBrake.
    for line in iter(process.stdout.readline, ''):
        # Filter the output: only show the line containing the encoding progress.
        if "Encoding: task" in line:
            # Print the line, but use '\r' (carriage return) as the end character.
            # This moves the cursor to the beginning of the current line, creating
            # an animated progress bar effect instead of spamming new lines.
            print(line.strip(), end='\r')

    process.stdout.close()
    return_code = process.wait() # Wait for the HandBrake process to fully complete.
    print() # Print a final newline to move past the progress bar.

    # 5. --- Result Handling and Cleanup ---
    if return_code == 0: # A return code of 0 means the process succeeded.
        print(f"\nSuccessfully encoded! File saved in the '{HANDBRAKE_OUTPUT_FOLDER}' folder.")
        try:
            os.remove(source_filepath) # Delete the original downloaded file.
        except OSError as e:
            print(f"ERROR: Failed to delete original file '{source_filepath}'. {e}")
    else: # Any other return code indicates an error.
        print("\n--- HANDBRAKE ERROR ---")
        print(f"Encoding failed. HandBrake exited with error code {return_code}.")


def download_youtube_video(url):
    """
    Downloads a YouTube video in the best available quality using yt-dlp.

    After a successful download, it triggers the HandBrake conversion process
    via a postprocessor hook.

    Args:
        url (str): The YouTube URL to download.
    """
    # This is a "hook" function that yt-dlp will call automatically
    # after it finishes a download and merge operation.
    def handbrake_postprocessor_hook(d):
        if d['status'] == 'finished':
            # Get the full path of the successfully downloaded file.
            filepath = d.get('info_dict', {}).get('filepath')
            if filepath and os.path.exists(filepath):
                # If the file exists, pass it to our conversion function.
                run_handbrake_conversion(filepath)

    # Configuration options for the yt-dlp downloader.
    yt_dlp_options = {
        # Select the best quality video and audio streams and merge them.
        'format': 'bestvideo+bestaudio/best',
        # Define the output filename template and save location (next to the .exe).
        'outtmpl': os.path.join(APP_DIR, '%(title)s.%(ext)s'),
        # Specify the final container format after merging.
        'merge_output_format': 'mp4',
        # Register our custom function to run after processing is complete.
        'postprocessor_hooks': [handbrake_postprocessor_hook],
        # Suppress all informational output from yt-dlp except for the progress bar.
        'quiet': True,
        'no_warnings': True,
    }

    # Execute the download. 'with' statement ensures resources are handled correctly.
    with yt_dlp.YoutubeDL(yt_dlp_options) as ydl:
        print(f"--- Starting YouTube download for: {url} ---")
        ydl.download([url])


# ==============================================================================
# MAIN EXECUTION
# ==============================================================================

def main():
    """
    The main application loop. It continuously prompts the user for URLs
    and processes them until they choose to exit.
    """
    while True:
        # 1. --- Display Prompt ---
        # Show a clean interface for the user to paste their link.
        print("\n" + "="*60)
        print("YouTube Downloader and Converter is ready.")
        print("Paste your YouTube URL below, or type 'exit' to close.")
        print("="*60)
        video_url = input("Enter URL: ")

        # 2. --- Validate Input ---
        # Check if the user wants to exit the application.
        if video_url.lower().strip() in ['exit', 'quit']:
            print("Exiting application. Goodbye!")
            break # Exit the 'while' loop.

        # Check if the user just pressed Enter without pasting a link.
        if not video_url.strip():
            print("No URL entered. Please try again.")
            continue # Skip to the next iteration of the loop.

        # 3. --- Process the URL ---
        # Use a try/except block to catch any errors during the download
        # or conversion process. This prevents a single bad link from
        # crashing the entire application.
        try:
            download_youtube_video(video_url)
        except Exception as e:
            print("\n--- AN UNEXPECTED ERROR OCCURRED ---")
            print(f"Failed to process URL: {video_url}")
            print(f"ERROR: {e}")
            # The following line is useful for debugging. It prints detailed error info.
            # traceback.print_exc()


# This is the standard entry point for a Python script.
# The code inside this block will only run when the script is executed directly.
if __name__ == "__main__":
    main()